# Generated by Django 4.2.1 on 2023-05-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shadow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="heartrate",
            field=models.IntegerField(default=60),
        ),
    ]
