# Generated by Django 4.2.1 on 2023-05-28 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shadow", "0002_patient_heartrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="heartrate",
            field=models.IntegerField(
                default=60,
                validators=[
                    django.core.validators.MinValueValidator(40),
                    django.core.validators.MaxValueValidator(160),
                ],
            ),
        ),
    ]
