# Generated by Django 4.2.1 on 2023-05-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WingManConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raid", models.CharField(max_length=154, null=True)),
                ("drivees", models.PositiveIntegerField(default=0)),
                ("init", models.CharField(max_length=154, null=True)),
                ("step_ref", models.CharField(max_length=154, null=True)),
                (
                    "expected_res",
                    models.CharField(blank=True, max_length=154, null=True),
                ),
            ],
        ),
    ]
